### PR TITLE
setTopText auto splits strings

### PR DESCRIPTION
**Pull request by edo9300**
#### What's changed?

Now the app should autmatically split the settings in the top screen.

#### Where have you tested it?

I couldn't test it because all my builds failed, and i couldn't properly configure docker on my pc, so i don't even know if it works as intended

*** 
#### Pull Request status
- [ ]  This PR has been tested using latest devkitPro, devkitARM, and EasyGL2D.  

_(Do not edit after this point)_
- [ ]  This PR is fully documented.
- [ ]  This PR has been tested before sending.
- [ ]  This PR follows C style and convention.

### CODE REVIEW

**Comment by Robz8** [comment]
This made spaces not visible. :(

**Comment by edo9300** [comment]
Ops, I fixed it, apparently I forgot to put the spaces in the final string

**Comment by NightYoshi370** [comment]
@RocketRobz so what's the status on this?

**Comment by RocketRobz** [comment]
I still haven't tested the latest changes.

**Comment by RocketRobz** [comment]
Finally got to test the latest changes. The last word in any description gets left out.

**Comment by edo9300** [comment]
@RocketRobz apparently it was a leftover I thought I already fixed

**Pull request merged**
