### PR TITLE
Custom DSi Menu/3DS Menu Themes

### PR DESCRIPTION
**Pull request by chyyran**
### What's changed?

This pull request implements #81 for the DSi Menu and 3DS Home Menu themes. Previously hardcoded paletted textures are now loaded from the SD card or NitroFS in the form of [Grit RIFF Format](https://www.coranac.com/man/grit/html/grit.htm) files.

#### Bugfixes and Performance Changes
* 3DS corner buttons are now baked into the background texture rather than loaded as `glSprites` to reduce flickering
* Top drawing fonts now also use a binary search (and thus rely on the LUT being in increasing sorted order of UTF16 codepoints)
* Most textures are now loaded once into RAM and drawn from RAM instead of being loaded from filesystem.

#### Refactorings and Changes
* Ported singleton settings and system details from `akmenu` and `settings`, bringing `dsimenu` in line for handling settings.
  * `cursorPosition[secondaryDevice]` and `pagenum[secondaryDevice]`, due to their frequent occurrence, now have macros defined for them `CURPOS` and `PAGENUM` that expand to `(ms().cursorPosition[ms().secondaryDevice])` and `(ms().pagenum[ms().secondaryDevice])` respectively.

* Moved most texture loading concerns and drawing routines into `ThemeTextures`
  * Photo loading, and the rotating cubes video remains in `graphics.cpp` due to heavy state requirements.
  * Time drawing remains reliant on `graphics.cpp` methods, but calls the underlying `ThemeTextures` time drawing routines 
  * SD Card Error Image loading, and RocketVideo image loading has not been changed due to the unique RAM requirements of loading those textures.
  * Font textures remain non-customizable and hardcoded.

* `ThemeTexture` loading routines are now dynamic from the data contained in the texture file.
  * In particular, palette size, and texture sizes are now determined by the the values written in the `PAL ` chunk header for the GRF file.
  * BMP file texture length is determined by reading the BMP header during load
  * All BMP files are loaded into buffers as raw BMP data instead of being re-read every time
    * The exception being background textures, which are stored into buffers as DS bitmap format. The raw BMP data is freed after being converted to DS bitmap.

* Some render positions for elements are now calculated from the `tc()` singleton, for theme configuration purposes.

* DSi and 3DS custom sub-theme select has been implemented in settings.

##### Adding a new texture
`ThemeTexture` is intended to handle most texture concerns. These are instructions on how to add a user-customizable loadable texture to the code.

1. Add the texture path and a fallback to `themefilenames.h` from which the texture will be loaded. The fallback should be loaded from NitroFS.
2. Allocate space for it in `ThemeTexture` by adding a `unique_ptr` class member of either `BmpTexture` or `GritTexture` for bitmap or paletted texture respectively. `u16[]` is also an option for a DS bitmap buffer, but note that `u16[]` unique pointers should be allocated in the constructor, for example
```cpp
_bottomBgImage = std::make_unique<u16[]>(BG_BUFFER_PIXELCOUNT);
```
whereas `GritTexture` and `BmpTexture` are dynamically sized and own their memory (thus respecting RAII)

3. Load the texture somewhere in `loadDsiTheme` or `load3DSTheme` using `make_unique`, for example
```cpp
_bipsTexture = std::make_unique<GritTexture>(TFN_GRF_BIPS, TFN_FALLBACK_GRF_BIPS);
```
4. *Effects* are functions that mutate the texture data. They can be applied with `applyEffect`. Currently, Bitmap effects are not in use, but the grayscale conversion done in `convertToDsBmp` could potentially be implemented with a Bitmap Effect.
  * `PaletteEffect`s mutate 16bit DS color format palette data
  * `BitmapEffect`s mutate raw Bitmap texture data, **not DS color format**. 

5. Raw texture data can be accessed by the `texture` method during a draw routine, or when loading into a `glSprite`.

### Creating Custom Themes (instructions for end users)

The easiest way of customizing a theme is by editing the BMP textures in a theme's *ui*, *battery*, or *volume* folder. These BMP textures must be in RGB565 format, and use `#FF00FF` as a transparent key color. BMP textures are allowed to vary in size, but may require tweaking of the theme configuration to render correctly (see below).

Changes to paletted textures are more involved. Within the *grit* folder of a theme, the various image files may be edited. You will also require [devkitPro](https://devkitpro.org) with GRIT installed. Once you have finished editing your files, you must run

```bash
$ make
```

In order to compile your themes into Grit RIFF Format. This will compile your paletted textures into **.grf** format in the *grf* folder.

Be aware the paletted textures come with more restrictions than BMP textures, the primary being an absolute maximum of 16 colors per texture. However, some textures may have even tighter default palette restrictions, which can be modified at the risk of running out of palette memory (see below).

#### Theme File Descriptions

*volume* and *battery* textures are self explanatory.

##### UI Textures
|Texture|Description|
|----------|---------------|
|bottom|The bottom background texture when not hovering over an icon|
|bottom_bubble|The bottom background texture when hovering over an icon|
|bottom_bubble_ds|For the 3DS theme, the bottom background texture when hovering over an icon when on a DS lite|
|bottom_ds|For the 3DS theme, the bottom background texture when not hovering over an icon when on a DS lite|
|date_time_font|The font to display the date and time|
|Lshoulder|The left shoulder|
|Lshoulder_greyed|The left shoulder when there are no pages to the left|
|Rshoulder|The right shoulder|
|Rshoulder_greyed|The right shoulder when there are no pages to the right|
|top|The top background|

##### Paletted Textures
|Texture|Description|Palette Restrictions (if less than 16)|
|-----|---|--|
|bips|The bips displayed on the bottom of the scrollbar (DSi Theme)| |
|launch_dot|The dots displayed when a game is launched (DSi Theme) | |
|moving_arrow|The arrow displayed when a game is being moved (DSi Theme)| |
|bubble|The bottom bit of the bubble that draws over the start border or icon box|8 Colors|
|box_empty|The texture displayed on an empty box (3DS Theme)|On the 3DS theme, the transparent color is `#E0DAD9` by default|
|box_full| The texture displayed on an empty box (3DS Theme)|On the 3DS theme, the transparent color is `#E0DAD9` by default|
|icon_gba|The icon displayed for GBARunner|The default transparent color is `#00FF00` |
|progress| The progress loading animation with 8 frames| 9 Colors|
|icon_gbamode|The icon displayed for native GBA Mode| |
|icon_md|The icon displayed for Mega Drive games| |
|wirelessicons|The icon displayed to indicate a game has wireless support|7 Colors|
|box|The box texture, containing both full and empty textures (for DSi Theme)| |
|start_text|The text displayed for the start border on the DSi Theme| 4 Colors|
|icon_unk|The icon displayed when a ROM is missing an icon| |
|brace| The brace texture for the DSi theme shown past the first and last icon| 4 Colors|
|start_border|The border with animation frames that indicates the selected icon (DSi Theme)|
|icon_gb|The icon displayed for Game Boy games| |
|cursor|The border with animation frames that indicate the selected icon (3DS Theme)| |
|icon_snes|The icon displayed for SNES ROMs| |
|icon_nes| The icon displayed for NES ROMs| |
|icon_gg|The icon that is displayed for Game Gear ROMs| |
|icon_settings|The icon that is displayed for Nintendo DSi Settings|
|icon_sms|The icon that is displayed for Sega Master System ROMs| |
|scroll_window|The part of the scrollbar that indicates the icons that are in view|7 Colors|
|cornerbutton|The buttons that are displayed on the SELECT menu (DSi Menu) The name of this texture is a misnomer.| |
|button_arrow|The textures for the arrows on either side of bottom scrollbar (DSi Theme)|
|small_cart|Small icon versions of the icons listed above| |
|dialogbox|The background of the dialog box that slides down| |
|folder|The icon for folders| |

#### Theme Configuration

You may configure various options on how the theme is drawn in the `theme.ini`, to accommodate larger sprites or textures.

|Value                          |Description                                  |Default (3DS)|Default (DSi)|
|-----------------------------|-----------------------------------------------------------|---|---|
|`StartBorderRenderY`|The initial Y position of the Start Border|92|81|
|`StartBorderSpriteW`| The width of the start border sprite. Note that the start border texture is exactly half of the full border. |32|32|
|`StartBorderSpriteH`|The height of the start border sprite|64|80|
|`TitleboxRenderY`|The initial Y position of the title text drawn|96|85|
|`BubbleTipRenderY`|The Y position of the tip of the bubble that is drawn over the start border|98|80|
|`BubbleTipRenderX`|The X position of the tip of the bubble that is drawn over the start border|125|22|
|`BubbleTipSpriteH`|The height of the bubble tip sprite|7|8|
|`BubbleTipSpriteW`|The width of the bubble tip sprite|7|11|
|`RotatingCubesRenderY`|The Y position on the top screen to draw the rotating cubes|78|N/A|
|`ShoulderLRenderY`|The Y position on the top screen to draw the left shoulder|172|172|
|`ShoulderLRenderX`|The X position on the top screen to draw the left shoulder|0|0|
|`ShoulderRRenderY`|The Y position on the top screen to draw the right shoulder|172|172|
|`ShoulderRRenderX`|The X position on the top screen to draw the right shoulder|178|178|
|`VolumeRenderX`|The X position on the top screen to draw the right shoulder|4|4|
|`VolumeRenderY`|The Y position on the top screen to draw the volume icon|16|16|
|`BatteryRenderY`|The Y position on the top screen to draw the battery icon|15|15|
|`BatteryRenderX`|The X position on the top screen to draw the battery icon|235|235|
|`RenderPhoto`|Whether or not to draw a photo on the top screen|0|1|
|`StartTextUserPalette`|Assign the DSi Profile Theme to the palette of the start text|N/A|1|
|`StartBorderUserPalette`|Assign the DSi Profile Theme Palette to the palette of the start border|N/A|1|
|`ButtonArrowUserPalette`|Assign the DSi Profile Theme Palette to the palette of the arrow buttons on the bottom of the screen|N/A|1|
|`MovingArrowUserPalette`|Assign the DSi Profile Theme Palette to the palette of the arrow shown when moving icons|N/A|1|
|`LaunchDotsUserPalette`|Assign the DSi Profile Theme Palette to the palette of the launch dots|N/A|1|
|`DialogBoxUserPalette`|	Assign the DSi Profile Theme Palette to the palette of the dialog box|N/A|1|
#### Advanced Theming

Occasionally, you may require more than the default number of colors for some paletted textures. In such cases, you may modify the `.grit` compilation file for the texture to increase the size of the palette.

For example, in `scroll_window.grit`, you may edit `-pn7` and change `7` to `16` for 16 colors. Be aware that if you remove the entire `-pn` line, you may encounter unexpected results.

Also note that the absolute maximum of 16 colors per texture is enforced in code and can not be modified. Even if you increase the number of palettes to above 16, no more than 16 colors worth of palette data will be loaded. With the amount of textures loaded in, there may not be enough palette memory to hold 16 colors worth of palettes for every texture. Keep this in mind when adjusting palette sizes.

Additionally, paletted textures must have dimensions that are a power of 2. Paletted textures sizes can not be changed except for `bubble` and `start_border`, which can have configurable sprite dimensions in `theme.ini`. However, note that doing so may have unexpected consequences.

Paletted textures are not checked for validity. An invalid texture should be rare if created with the provided makefile, but in certain cases a corrupted texture will cause the menu to not load at all.

The 3DS theme loads its rotating cubes animation from the file located at `/video/3dsRotatingCubes.rvid` in RocketVideo format. If you wish for this not to draw for theme purposes, the file can simply be deleted.

### Where have you tested it?

Nintendo DSi Hardware
*** 
#### Pull Request status
- [x]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.  

_(Do not edit after this point)_
- [ ]  This PR is fully documented.
- [ ]  This PR has been tested before sending.
- [ ]  This PR follows C style and convention.

### CODE REVIEW

**Comment by NightYoshi370** [comment]
Shouldn't you do all the refactoring changes you're doing to the dsi theme to the r4 theme as well?

**Comment by chyyran** [comment]
> Shouldn't you do all the refactoring changes you're doing to the dsi theme to the r4 theme as well?

I feel that it is outside the scope of the PR, and I probably won't have time to work on this after I finish with this PR, but you're free to cherrypick the changes off the branch and apply them to the R4 theme.

**Comment by NightYoshi370** [comment]
BTW, just letting you know that there are 3 conflicting files.

**Comment by chyyran** [comment]
...and that should be everything!

**Pull request merged**
