### PR TITLE
A few changes to make Azure work

### PR DESCRIPTION
**Pull request by Epicpkmn11**
#### What's changed?

- Add the Azure status picture to the readme (@FlameKat53 )
- Remove `libnds.7z`
- Add `libmm7.a` (fixes devkitARM r51)
- Add the azure file?? (I already updated it, but this claims to be adding it  ¯\\\_(ツ)_/¯ )

#### Where have you tested it?

This fork, [Azure](https://dev.azure.com/ds-homebrew/Builds/_build/results?buildId=237) / [TWLBot](https://github.com/TWLBot/Builds/releases/tag/v20190316-033111)

I tested the builds yesterday on my DSi and DS Lite and they worked, haven't tried today on devkitARM r52, but it *should* work

*** 
#### Pull Request status
- [x]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.  

_(Do not edit after this point)_
- [ ]  This PR is fully documented.
- [ ]  This PR has been tested before sending.
- [ ]  This PR follows C style and convention.

### CODE REVIEW

**Comment by Epicpkmn11** [comment]
If you don't want 130 commits of Azure, close this and I'll do another PR in another fork with just a single commit

**Comment by FlameKat53** [comment]
Currently, main.srldr doesn’t boot into settings.srldr or any theme’s .srldr file.
Though, naming a file such as dsimenu.srldr to main.srldr will work, so does settings and all other themes, it’s just main.srldr that doesn’t work

**Comment by FlameKat53** [comment]
Oh I forgot to say I tried on my DS Lite with an R4i-SDHC Card

**Comment by Epicpkmn11** [comment]
^ works fine on 3DS / DSi / TTDS / chyyran's flashcard

**Comment by NightYoshi370** [comment]
I cannot rebase and merge. Can you please make a new PR with only one commit?

**Comment by edo9300** [comment]
@NightYoshi370 wouldn't squash and merge do it?

**Comment by NightYoshi370** [comment]
I'm dumb

**Pull request merged**
