### PR TITLE
Remove launchargs files from 7z (for TWLBot)

### PR DESCRIPTION
**Pull request by FlameAlt53**
read title

### CODE REVIEW

**Comment by NightYoshi370** [comment]
Didn't launcharg support get removed?

**Comment by FlameAlt53** [comment]
yes, and they are useless, and taking up screen space in twilight menu++ nightlies [here](https://github.com/TWLBot/Builds/releases)

**Comment by NightYoshi370** [comment]
screen space? What?

**Comment by FlameAlt53** [comment]
screen space as in this [this](https://drive.google.com/open?id=1snZ4dEg9XXkRjU0i49yRU4A0RJXKCfc90

**Comment by NightYoshi370** [comment]
404 not found

**Comment by FlameAlt53** [comment]
fixed

**Comment by NightYoshi370** [comment]
...still a 404.
Just upload it here

**Comment by FlameAlt53** [comment]
! #[img](https://drive.google.com/file/d/1snZ4dEg9XXkRjU0i49yRU4A0RJXKCfc9/view?usp=sharing0

**Pull request merged**
