### PR TITLE
fix launch orbs' positions

### PR DESCRIPTION
**Pull request by piratesephiroth**
#### What's new?

Nothing

#### What is fixed?

Fix the position of the orbs used in DSi Menu's game launching animation

#### Where have you tested it?

Can't test because it does not build properly on the latest devkitpro. All I get is a white screen, even if I build gl2d myself.

*** 
#### Pull Request status
- [x]  This PR has been tested using latest devkitPro, devkitARM, and EasyGL2D. 

_(Do not edit after this point)_
- [ ]  This PR is fully documented.
- [ ]  This PR has been tested before sending.
- [ ]  This PR follows C style and convention.

### CODE REVIEW

**Comment by RonnChyran** [comment]
Try building with Docker. Also the position of the dots are still off.

**Comment by Robz8** [comment]
Yeah, the actual rotation code needs to be changed so that the dots rotate in a circle.

**Comment by piratesephiroth** [comment]
@RonnChyran, can you comment out the launchDotXMove[] and launchDotYMove[] lines and build again?

**Comment by NightYoshi370** [comment]
@RocketRobz do you mind testing this?

**Comment by NightYoshi370** [comment]
Wait, why was this closed?

**Comment by RocketRobz** [comment]
Judging by the code, it doesn't animate, and there doesn't seem to be more commits coming from this.

**Comment by piratesephiroth** [comment]
yeah, I could never build a working version to test it so I could not move forward

**Comment by flutterbrony** [comment]
What I get compiling your branch is a "Guru Meditation Error! data abort!" on my dsi, and it work ok on rocketrobz master branch.

**Pull request closed without merging**
